[package]
name = "metro"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
ssh2 = "0.9"
ctrlc = "3.4"
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
tempfile = "3"
